<?= $this->parent() ?>
<?= $this->render('/element/form-item', array(
	'type'		=> 'textarea',
	'entity'	=> $entity,
	'name'		=> 'body',
	'label'		=> 'Content',
	'class'		=> 'monospaced editor-content',
	'rows'		=> 20,
), 'core') ?>
<?= $this->render('/element/form-item', array(
	'type'		=> 'input_chalk',
	'entity'	=> $entity,
	'name'		=> 'image',
	'label'		=> 'Image',
	'filters'	=> 'core_image',
), 'core') ?>
<?= $this->render('/element/form-item', array(
	'type'		=> 'textarea',
	'entity'	=> $entity,
	'name'		=> 'summary',
	'label'		=> 'Summary',
	'class'		=> 'monospaced editor-content',
	'rows'		=> 5,
), 'core') ?>
<?= $this->render('/element/form-item', array(
	'entity'	=> $entity,
	'name'		=> 'categories',
	'label'		=> 'Categories',
    'values'    => $this->em('article_category')->all(),
    // 'values'    => $this->em($this->module->name('category'))->all(),
), 'core') ?>
<?= $this->render('/element/form-item', array(
	'entity'	=> $entity,
	'name'		=> 'author',
	'label'		=> 'Author',
	'type'		=> 'select',
	'null'		=> 'None',
	'values'	=> $this->em('core_user')->all(),
), 'core') ?>